[metadata]
name = twowaypanel
version = attr: twowaypanel.__version__
author = Zizhong Yan
author_email = helloyzz@gmail.com
description = A Python package for econometric analysis of nonlinear panel models with two-way fixed effects
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/zizhongyan/twowaypanel
license = MIT
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

project_urls =
    Source = https://github.com/zizhongyan/twowaypanel
    Documentation = https://twowaypanel.readthedocs.io/
    Issues = https://github.com/zizhongyan/twowaypanel/issues

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
zip_safe = False
install_requires =
    numpy
    scipy
    pandas
    statsmodels
    tqdm
    matplotlib
    seaborn
    torch

[options.packages.find]
include =
    twowaypanel
    twowaypanel.*
exclude =
    tests
    tests.*
